#!/usr/bin/env node
// Renders <tag>.md (+ OFFENDERS.md for tag "before", OFFENDERS-<tag>.md otherwise) from <tag>.json. Usage: node report.mjs <path/to/tag.json>
import fs from 'node:fs';
import path from 'node:path';
const file = path.resolve(process.argv[2]), dir = path.dirname(file), tag = path.basename(file, '.json');
const R = JSON.parse(fs.readFileSync(file, 'utf8'));
const f1 = (x) => (x == null ? '-' : typeof x === 'number' ? (Math.abs(x) >= 100 ? String(Math.round(x)) : String(+x.toFixed(1))) : String(x));
const tbl = (head, rows) => ['| ' + head.join(' | ') + ' |', '|' + head.map((h, i) => (i ? '---:' : ':---')).join('|') + '|', ...rows.map((r) => '| ' + r.map((c) => (c == null ? '-' : c)).join(' | ') + ' |')].join('\n');
const REQ = [['idle', 'idle 10 s'], ['spins10', '10 normal spins'], ['cascade', null], ['intro', 'bonus intro (PLACE THE CALL)'], ['bought', 'full bought bonus (confirm -> SPIN accepting)'], ['more', 'ONE MORE CALL prompt 8 s']];
const TOL1 = 17.0, TOL4 = 33.6;   // 60 Hz frames arrive 16.7 +- 0.1 ms apart (idle p50 16.7, p95 16.8), so "p95 < 16.7" is read as "locked to 60 Hz" = p95 <= 17.0; 4x: two vsyncs = 33.3, tolerance 33.6
const rowsOf = (s) => (s && s.rows) || [];
const find = (pass, key, name) => { const s = (R.passes[pass] || []).find((x) => x.key === key); return s && (name ? rowsOf(s).find((r) => r.name === name) : rowsOf(s)[0]); };
const st = (r) => { const c = r.trace && r.trace.compositor; if (!c || !c.states) return '-'; const A = c.states.STATE_PRESENTED_ALL || 0, P = c.states.STATE_PRESENTED_PARTIAL || 0, D = c.states.STATE_DROPPED || 0, I = c.states.STATE_NO_UPDATE_DESIRED || 0, tot = A + P + D;
  return `${A}/${P}/${D}` + (tot && P ? ` (${Math.round(100 * P / tot)}% partial)` : '') + (I ? ` +${I} idle` : ''); };
function frameTable(pass, tol) {
  const out = [];
  for (const s of R.passes[pass] || []) {
    if (s.error) { out.push([s.title || s.key, 'FAILED: ' + s.error, '', '', '', '', '', '', '', '', '']); continue; }
    for (const r of rowsOf(s)) out.push([(s.key === 'idle' || /^  /.test(r.name) ? '' : '**') + (r.name.startsWith('  ') ? '&nbsp;&nbsp;' + r.name.trim() : r.name) + (s.key === 'idle' || /^  /.test(r.name) ? '' : '**'), r.frames, f1(r.p50), f1(r.p95), f1(r.p99), f1(r.worst), r.over16_7, r.over25, r.over33, `${r.longtasks}/${f1(r.longtaskWorst)}`, st(r)]);
  }
  return tbl(['scene / window', 'frames', 'p50 ms', 'p95 ms', 'p99 ms', 'worst ms', '>16.7', '>=25', '>33', 'long tasks n / worst ms', 'compositor presented-all / partial / dropped'], out);
}
const verdict = (pass, tol, strict = true) => REQ.map(([k, n]) => { const r = find(pass, k, n); if (!r) return `- ${n || k}: NOT MEASURED`; const ok = (!strict || r.over33 === 0) && r.p95 <= tol; return `- ${n || r.name}: ${ok ? 'PASS' : 'FAIL'} (p95 ${f1(r.p95)} ms, ${r.over33} frames over 33 ms, worst ${f1(r.worst)} ms)`; }).join('\n');

let md = `# COLD CALL FB5 frame-time results: ${tag}\n\n`;
md += `Build under test: ${R.base}  \nRun: ${R.startedAt} (${R.elapsedS}s), viewport ${R.viewport.w}x${R.viewport.h} css px, device scale ${R.viewport.dpr}${(R.passes[Object.keys(R.passes)[0]] || [])[0] && (R.passes[Object.keys(R.passes)[0]] || [])[0].dprActual ? ' (measured devicePixelRatio ' + (R.passes[Object.keys(R.passes)[0]] || [])[0].dprActual + ')' : ''}, seed ${R.seed} (practice rounds are seeded through crypto.getRandomValues, so a re-run plays the same rounds on the same code)  \n`;
md += `GPU (verified before any scene ran): **${R.gpu.pageWebglRenderer}**, driver ${R.gpu.devices[0]}; Chrome ${R.gpu.chrome} ${R.gpu.headful ? '(headful window parked off-screen: real window + DWM presentation, nothing visible)' : '(headless=new)'}; gpu_compositing ${R.gpu.gpuCompositing}, rasterization ${R.gpu.rasterization}. The rig refuses to write results on any other renderer (exit 3).\n\n`;
md += `## What each number is\n- **p50 / p95 / p99 / worst ms**: \`requestAnimationFrame\` frame-start deltas (the rAF timestamp argument, which is the compositor's BeginFrame time), recorded by a loop injected before any game script, taken only inside the scene's window (setup and waits excluded; a frame counts only when the previous frame is also inside the window). The display is 60 Hz, so frames arrive 16.7 ms apart and a missed vsync shows as 33.3 ms. This is main-thread frame cadence, not GPU execution time.\n- **>16.7**: literal count of deltas over 16.7 ms. At 60 Hz this counts vsync jitter (idle: p50 16.7, p95 16.8), so it is not a stutter count. **>=25** (at least one vsync missed) and **>33** (the brief's number; two vsyncs) are the ones to read.\n- **long tasks n / worst**: PerformanceObserver 'longtask' (main-thread task over 50 ms) inside the window. long-animation-frame entries are in the JSON (\`loaf\`, with script / style+layout / render split and the slowest scripts).\n- **compositor presented-all / partial / dropped**: cc PipelineReporter frame outcomes from a Chrome trace (category disabled-by-default-devtools.timeline.frame only, calibration below): PRESENTED_ALL = every update made it, PRESENTED_PARTIAL = presented without the latest main-thread update (the main thread was late, so anything driven by main-thread work, such as paint-based CSS animations and per-frame JS tweens, lagged a frame), DROPPED = nothing presented. "idle" = no update wanted. This is the real compositor result per frame. (The BeginImplFrame-to-presented latency is a constant 33 ms with a vsync pipeline two deep, so it is in the JSON but not used.)\n\n`;
const tov = R.traceOverheadCheck; if (tov) md += `Calibration, idle 10 s with and without the light trace: p50 ${f1(tov.noTrace.p50)} -> ${f1(tov.lightTrace.p50)}, p95 ${f1(tov.noTrace.p95)} -> ${f1(tov.lightTrace.p95)}, worst ${f1(tov.noTrace.worst)} -> ${f1(tov.lightTrace.worst)}, >=25 ms ${tov.noTrace.over25} -> ${tov.lightTrace.over25}.\n\n`;
const P1 = R.passes.timing_1x ? 'timing_1x' : 'timing_1x_first';
md += `## Real GPU, no throttle, ${P1 === 'timing_1x' ? 'steady state' : 'FIRST run only (--no-steady)'} (${R.viewport.w}x${R.viewport.h}; ${P1 === 'timing_1x' ? 'second run of every scene in the same browser, GPU caches warm' : 'fresh Chrome profile, cold GPU caches'})\n\n${frameTable(P1, TOL1)}\n\nBar from the brief (0 frames over 33 ms, p95 at 60 Hz = <= ${TOL1} ms):\n${verdict(P1, TOL1)}\n\n`;
if (R.passes.timing_1x_first && R.passes.timing_1x) md += `## Real GPU, no throttle, FIRST encounter (fresh Chrome profile: cold GPU shader / decode caches, what a new player's first minute looks like)\n\n${frameTable('timing_1x_first', TOL1)}\n\nSame bar:\n${verdict('timing_1x_first', TOL1)}\n\n`;
if (R.passes.timing_4x) md += `## Same scenes, CPU throttled 4x (Emulation.setCPUThrottlingRate 4; stands in for a phone, GPU still the 5090)\n\n${frameTable('timing_4x', TOL4)}\n\nBar from the brief (p95 under 33 ms, read as <= ${TOL4}; single missed frames are listed but do not fail this bar):\n${verdict('timing_4x', TOL4, false)}\n\n`;
if (R.passes.timing_phone_540x960_dpr2) md += `## Phone-shaped viewport 540x960 at dpr 2, no throttle (idle, 10 spins, ONE MORE CALL only)\n\n${frameTable('timing_phone_540x960_dpr2', TOL1)}\n\n`;
const spins = (R.passes[P1] || []).find((s) => s.key === 'spins10');
if (spins && spins.info && spins.info.rows) md += `10 normal spins, per spin (1x steady): ${spins.info.rows.map((x) => `#${x.i} ${x.ms} ms${x.bonus ? ' BONUS ' + x.bonus : ''}${x.win ? ' win ' + x.win : ''}`).join('; ')}\n\n`;
// first load
if (R.firstLoad) { const c = R.firstLoad.cold, w = R.firstLoad.warm;
  md += `## First load and time to first spin (over the tailnet, shaman -> this box, ${R.base.split('/').slice(0, 3).join('/')})\n\n`;
  md += tbl(['', 'cold cache', 'warm reload'], [['game ready (assets decoded, SPIN usable), ms from navigation start', c.readyAtMs, w.readyAtMs], ['index.html response end, ms', f1(c.nav.responseEnd), f1(w.nav.responseEnd)], ['requests', c.requests, w.requests], ['transferred KB', c.transferKB, w.transferKB], ['encoded body KB / decoded KB', `${c.bodyKB} / ${c.decodedKB}`, `${w.bodyKB} / ${w.decodedKB}`], ['last byte at, ms', c.lastByteMs, w.lastByteMs], ['PICK UP click to SPIN click, ms (scripted wait)', c.firstSpin.splashToSpinClickMs, w.firstSpin.splashToSpinClickMs], ['first spin, click to SPIN accepting again, ms', c.firstSpin.firstSpinMs, w.firstSpin.firstSpinMs]]) + '\n\n';
  if (c.cold_ === undefined && R.firstLoad.coldRuns) md += `Cold loads measured ${R.firstLoad.coldRuns.length} times, cache cleared each time (the table is the median-ready one): ready ${R.firstLoad.coldRuns.map((x) => x.readyAtMs).join(' / ')} ms, last byte ${R.firstLoad.coldRuns.map((x) => x.lastByteMs).join(' / ')} ms, first spin ${R.firstLoad.coldRuns.map((x) => x.firstSpinMs).join(' / ')} ms.\n\n`;
  md += `Time to first spin (cold) = ready ${c.readyAtMs} ms + a human click on PICK UP + the SPIN click; the first round then takes ${c.firstSpin.firstSpinMs} ms. By type (cold): ${Object.entries(c.byType).map(([k, v]) => `${k} ${v.n} files ${v.bodyKB} KB`).join(', ')}. Response headers: ${Object.entries(c.headers).map(([k, v]) => `${k}: ${v.cacheControl}, content-encoding ${v.encoding}`).join('; ')}. Largest files: ${c.top.slice(0, 6).map((t) => `${t.url} ${t.kb} KB`).join(', ')}.\n\n`;
  md += `Rig artifact, not a game number: the first request after Chrome starts stalls 5-23 s before it is sent (resource timing requestStart; curl from the same PC takes 25 ms), so the rig warms the browser with one request first and loads are measured after that.\n\n`; }
// profile
if (R.passes.profile_1x) {
  md += `## Where the time goes (full Chrome trace per window, 1x; the trace itself slows the page, so read the shares, not the absolute frame times)\n\n`;
  const rowsP = []; for (const s of R.passes.profile_1x) for (const r of rowsOf(s)) { const t = r.trace; if (!t || !t.main) continue; const m = t.main.selfMs; rowsP.push([r.name.trim(), `${t.main.busyPct}%`, f1(m.script), f1(m.style), f1(m.layout), f1(m.paint), f1(m.commit), f1(m.other), f1(t.raster.perSecMs), f1(t.gpuProcess.perSecMs), t.paint.paintedAreaPerSecInViewports, f1(t.framePhases.StyleAndLayout.p95), f1(t.framePhases.Render.p95)]); }
  md += tbl(['window', 'main thread busy', 'script ms', 'style ms', 'layout ms', 'paint ms', 'commit ms', 'other ms', 'raster threads ms/s', 'GPU-process thread ms/s', 'painted area per s (viewports)', 'style+layout p95 ms/frame', 'render p95 ms/frame'], rowsP) + '\n\n';
  md += `Ms columns are exclusive main-thread self time inside the window. Raster = RasterTask on the raster worker threads; GPU-process = CrGpuMain thread busy (command decode and submit, not shader execution time). Painted area per second = sum of Paint-event clip areas / viewport area / seconds (1.0 = the whole screen repainted once a second; 60 = every frame).\n\n`;
}
for (const [pn, lab] of [['profile_1x_first', 'FIRST encounter (cold GPU caches)'], ['profile_1x', 'steady']]) if (R.passes[pn]) {
  const A_ = []; for (const s of R.passes[pn]) for (const r of rowsOf(s)) for (const a of r.autopsy || []) A_.push([r.name.trim(), a.dtMs, f1(a.atMs / 1000) + ' s', a.mainBusyPctOfGap + '%', a.biggestMainEvents.map((e) => `${e.name} ${e.ms} ms${e.detail ? ' (' + e.detail + ')' : ''}`).join('; ') || '-', `${a.gpuBusyMs} / ${a.rasterMs}${a.gpuTopEvents && a.gpuTopEvents.length ? ' [' + a.gpuTopEvents.join('; ') + ']' : ''}`, a.verdict]);
  const n25 = R.passes[pn].reduce((a, s) => a + rowsOf(s).reduce((b, r) => b + (r.over25 || 0), 0), 0);
  md += `## Worst-frame autopsy, ${lab} (profile pass: every rAF gap >= 25 ms; what the main thread, GPU process and raster threads were doing inside that gap)\n\n` + (A_.length ? tbl(['window', 'gap ms', 'at', 'main busy', 'biggest main-thread events', 'GPU-proc / raster busy ms', 'verdict'], A_) : `No frame gap >= 25 ms (${n25} counted in the pass).`) + '\n\n';
}
if (R.coldAblation && R.coldAblation.length) {
  md += `## Cold-start hitch experiment (one Chrome launch per row, scenes 10 spins -> big win -> bonus intro in that order)\n\n`;
  const rows = R.coldAblation.map((c) => c.error ? [c.variant, 'FAILED: ' + c.error, '', '', ''] : [c.variant, c.rows.reduce((a, r) => a + (r.over25 || 0), 0), c.rows.reduce((a, r) => a + (r.over33 || 0), 0), f1(Math.max(...c.rows.map((r) => r.worst || 0))), c.rows.filter((r) => r.over25).map((r) => `${r.name.replace(/\(.*/, '').slice(0, 26)}: ${r.over25}x, worst ${f1(r.worst)}`).join('; ') || 'none']);
  md += tbl(['launch', 'frames >=25 ms (all windows)', 'frames >33 ms', 'worst frame ms', 'windows with a miss'], rows) + '\n\nThe hitch is a first-use cost in the GPU process (see the autopsy), so each row is a sample, not a rate: compare the control rows with each other first (that is the run-to-run spread), and read a variant as a cause only if it is clearly outside that spread.\n\n';
}
if (R.ablation && R.ablation.length) {
  md += `## Kill-switch experiments (full-trace windows, same seed; one CSS rule injected after load disables a property everywhere)\n\n`;
  for (const scene of ['idle', 'cascade']) { const rows = R.ablation.filter((a) => a.scene === scene && a.rows); if (!rows.length) continue; const ctl = rows.find((a) => a.variant === 'control');
    md += `### ${scene}\n\n` + tbl(['variant', 'window', 'main busy %', 'delta vs control', 'raster ms/s', 'GPU-proc ms/s', 'painted area/s', 'p95 ms', '>=25'], rows.flatMap((a) => a.rows.map((r, i) => { const c = ctl && ctl.rows[i]; return [a.variant, r.name, r.trace && r.trace.main ? r.trace.main.busyPct : '-', c && r.trace && r.trace.main && c.trace && c.trace.main ? f1(r.trace.main.busyPct - c.trace.main.busyPct) : '', r.trace && r.trace.raster ? f1(r.trace.raster.perSecMs) : '-', r.trace && r.trace.gpuProcess ? f1(r.trace.gpuProcess.perSecMs) : '-', r.trace && r.trace.paint ? r.trace.paint.paintedAreaPerSecInViewports : '-', f1(r.p95), r.over25]; }))) + '\n\n'; }
}
md += `## Not provable with this rig\n- Real compositor frame times are only known through trace frame outcomes (presented / partial / dropped); GPU shader-execution time is not exposed by Chrome tracing, so GPU cost is the GPU-process thread busy time and the raster-thread time.\n- 60 Hz display only (the 5090 is attached to a 60 Hz 4K panel): a 144 Hz player has tighter frame budgets and would show the same misses as 6.9 ms multiples.\n- A 5090 is 10-20x a typical laptop GPU; 4x CPU throttle models a slower CPU only. GPU-bound costs (large blurred drop-shadows, full-screen repaints) are understated for integrated GPUs.\n- The rig's own rAF loop forces a frame every vsync, so 'idle' frame time is cadence of an always-ticking page; a browser with no animation would skip frames.\n- Chris's PC may be doing other work during a run: nvidia-smi before each Chrome launch is recorded under gpu.sessions[].nvidiaSmiBeforeLaunch in the JSON (utilization %, MiB, W, MHz) and printed in the run log; a busy GPU there means the numbers are polluted.\n- Practice mode only (local engine, no server round-trip, no leads/pull UI). The pull UI is covered only by the mock=pull scenes; live-server decisions are not driven.\n`;
fs.writeFileSync(path.join(dir, tag + '.md'), md);
console.log('wrote', path.join(dir, tag + '.md'));
import('./offenders.mjs').then((m) => m.write(R, dir, tag)).catch((e) => console.log('offenders:', e.code === 'ERR_MODULE_NOT_FOUND' ? 'offenders.mjs not present' : e.stack));
